version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=eventticketing
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRY=24h
      - MOMO_API_KEY=your-momo-api-key
      - MOMO_API_SECRET=your-momo-api-secret
      - MOMO_ENVIRONMENT=sandbox
      - SMS_API_KEY=your-sms-api-key
      - SMS_API_SECRET=your-sms-api-secret
      - SMS_SENDER_ID=EventTix
      - USSD_CODE=*123#
      - USSD_SESSION_TIMEOUT=300
      - ADMIN_EMAIL=admin@eventticketing.com
      - ADMIN_PASSWORD=admin123
      - ADMIN_PHONE=+1234567890
      - COMMISSION_RATE=0.05
      - ENABLE_USSD=true
      - ENABLE_QR=true
      - ENABLE_SMS=true
      - ENABLE_EMAIL=false
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    depends_on:
      - mongo
    volumes:
      - ./uploads:/root/uploads
    restart: unless-stopped
    networks:
      - eventticketing-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=eventticketing
    volumes:
      - mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - eventticketing-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - eventticketing-network

volumes:
  mongo_data:

networks:
  eventticketing-network:
    driver: bridge 